name: pet_home_app
description: An open source to help finding a home for pets.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.0
  http: ^0.13.4
  flutter_form_builder: ^7.1.0
  form_builder_image_picker: ^2.0.0
  form_builder_validators: ^7.4.0
  mask_text_input_formatter: ^2.1.0
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^5.0.2
  geolocator: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
